import type {Metadata} from 'next';
import { ThemeProvider as NextThemesProvider } from "next-themes";
import './globals.css';
import { Toaster } from "../components/ui/toaster"

export const metadata: Metadata = {
  title: 'Linguistic Decoder',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <NextThemesProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
        </NextThemesProvider>
      </body>
    </html>
  );
}
